# Generated by Django 4.0.2 on 2022-02-23 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0002_alter_rating_username_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='Professor',
        ),
        migrations.AddField(
            model_name='module',
            name='professor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
