# Generated by Django 4.0.2 on 2022-02-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_remove_module_professor_module_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='professor',
            field=models.ManyToManyField(to='rate.Professor'),
        ),
    ]
