# Generated by Django 4.0.2 on 2022-02-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_alter_module_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='profesesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rate.professor'),
            preserve_default=False,
        ),
    ]
