# Generated by Django 4.0.2 on 2022-02-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_rating_profesesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
