# Generated by Django 4.0.2 on 2022-03-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0008_alter_professor_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='profesesor',
            new_name='professor',
        ),
    ]
