# Generated by Django 4.0.2 on 2022-03-14 18:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0010_rename_code_rating_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='module',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='module',
            name='year',
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(default=django.utils.timezone.now)),
                ('semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.module')),
                ('professor', models.ManyToManyField(to='rate.Professor')),
            ],
        ),
    ]
