# Generated by Django 4.0.2 on 2022-03-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0011_remove_module_professor_remove_module_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.moduleinstance'),
        ),
    ]
