# Generated by Django 4.0.2 on 2022-03-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0012_alter_rating_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinstance',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
